### ISSUE TITLE
Question regarding funny link

### ISSUE THREAD

**Issue by leoheitmannruiz** [noqqe/why-openbsd.rocks#101]
Hey,

I'm curious: what's up with this link? And do you want to replace it with the URL of the page it redirects to?

https://github.com/noqqe/why-openbsd.rocks/blob/3a32b99d32fc7504c9037e2f8df543662dec4330/content/fact/doas.md?plain=1#L17

**Comment by noqqe** [comment]
eww where does this come from :/ 

nice find!
