### ISSUE TITLE
i18n?

### ISSUE THREAD

**Issue by quobit** [noqqe/why-openbsd.rocks#63]
Hi Florian!

First of all, thanks a lot for "Why OpenBSD rocks!". I'd like to know if applying i18n is in your plans.

Thank you.

**Comment by noqqe** [comment]
Hi! 

Nice to hear you like it :) 

To be honest I don't plan to support multiple languages as this gets fairly often outdated and unmaintained. 

I feel even more confident about this when I think about OpenBSD OS itself, which also does not provide any translations and therefore users need to be capable of understanding the english language. 

Hope you understand

**Comment by quobit** [comment]
You're right
