### ISSUE TITLE
Subdomain why.openbsd.rocks

### ISSUE THREAD

**Issue by h3artbl33d** [noqqe/why-openbsd.rocks#82]
I really like `why-openbsd.rocks`, as the registrant of `openbsd.rocks`, would you perhaps be interested in the subdomain `why.openbsd.rocks`? I can setup the DNS for you to point to the current A and AAAA records; you'll need to add it to `httpd.conf` and run `acme-client` obviously :)

**Comment by noqqe** [comment]
Hi! :) 

of course, would be very nice. Could you setup an CNAME to why-openbsd.rocks?

**Comment by h3artbl33d** [comment]
Of course! The CNAME is setup! I will keep it intact as long as I am the registrant of `openbsd.rocks` - and I plan to remain that for an indefinite period :)

**Comment by noqqe** [comment]
Nice! I put the config in httpd(8) and refresehd the certificates with the alias for why.openbsd.rocks

Since there is js involved, we now run into CORS problems. I think I need to setup a relayd(8) to set cross-origin headers.

**Comment by h3artbl33d** [comment]
There is an easier fix, you could make the paths relative. Like `<link href="https://why-openbsd.rocks/css/styles.css" media="all" rel="stylesheet" />` => `<link href="/css/styles.css" media="all" rel="stylesheet" />`;) Also, Matomo needs to be configured to allow it, right now the tracking code is `_paq.push(["setDomains", ["*.why-openbsd.rocks","*.why-openbsd.rocks"]]);`.

But a more resilient way would be to setup `relayd(8)` to allow cross-origin headers yeah :)

![Javascript is the root of all evil](https://h3artbl33d.nl/jscript.jpg)

**Comment by hucste** [comment]
What is your SSG? It seems Hugo? If yes, think to change your baseURL variable into the file config.

**Comment by noqqe** [comment]
Done using the hugo solution of removing the `baseurl` config item from `config.toml`

**Comment by noqqe** [comment]
It works :) https://why.openbsd.rocks/

**Comment by hucste** [comment]
Why are you closed this?

It seems no redirection from why-openbsd.rocks to the new domain, or not run correctly.

And perhaps, you do change a little the title in "Why.OpenBSD.Rocks!" into the webpages? no?

**Comment by noqqe** [comment]
It was never intended that we switch the sites name - why.openbsd.rocks is an alias to why-openbsd.rocks :) 
I planned to tweet something about in a few days :)

**Comment by jaywilliams** [comment]
Thanks for the clarification @noqqe, I saw @hucste mention the header change so I figured I'd submit a pull request for it.

**Comment by noqqe** [comment]
no worries :) thanks both of you anyways! :)
