### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by demostanis** [noqqe/why-openbsd.rocks#85]
https://why-openbsd.rocks/fact/dump/
The link to the man page is https://man.openbsd.org/dump.1 while it should be https://man.openbsd.org/dump.8

**Comment by hucste** [comment]
Fixed on [commit 8d9ddc6066c5134e4eb758d64817e6a7609e9be7](https://github.com/noqqe/why-openbsd.rocks/commit/8d9ddc6066c5134e4eb758d64817e6a7609e9be7)!
Need to deploy! ;-)

**Comment by noqqe** [comment]
automatic deploy was successful :)

**Comment by artsi0m** [comment]
My bad, thank you.
