### ISSUE TITLE
Broken link under dump utility fact

### ISSUE THREAD

**Issue by teito-dev** [noqqe/why-openbsd.rocks#88]
Hi,
The chflag link in the “dump” utility located under content/fact/dump.md is broken

This is the broken link can be found under here in the chflags tag : 
https://why-openbsd.rocks/fact/dump/

which points to:
https://why-openbsd.rocks/man.openbsd.org/chflags.1#nodump

It returns an 404 for me

I guess the correct link should be
https://man.openbsd.org/chflags.1#nodump

Also thanks a lot for making the site !
It’s really lovely,
Have a great day !

I would submit a PR for this but I’m not on PC for the week, extremely sorry

**Comment by teito-dev** [comment]
After further looking the error is due to a missing / in the url on the last line of content/facts/dump.md

its missing a slash in the https

Right now its, https:/
When it should be https://

Which is causing the link to break when hugo renders it

**Comment by hucste** [comment]
Ty!

Fixe on efbe6f8ce0e81c067aa94205eb8e7653da5f39c6
